awell-health/ui-library

package.json
src/hooks/useWizardForm/types.ts
src/hooks/useWizardForm/useWizardForm.tsx
src/organisms/wizardForm/__testdata__/testFormFixture.ts
src/organisms/wizardForm/wizardForm.spec.tsx
src/organisms/wizardForm/wizardForm.stories.tsx

https://awellhealth.atlassian.net/browse/AST-4510

AST-4510: navigation between required questions is broken in 0.0.40

---

.vscode/ui-library.code-workspace
package.json
src/atoms/index.ts
src/atoms/modal/Modal.module.scss
src/atoms/modal/Modal.stories.tsx
src/atoms/modal/Modal.tsx
src/atoms/modal/index.tsx
src/globalStyles/_index.scss
src/hostedPages/layouts/HostedPageLayout/HostedPageLayout.stories.tsx
src/index.ts
yarn.lock

https://www.loom.com/share/bf9f90ce095a49099a6afaa97a8ad852

AST-4622: modal component

---

package.json
src/atoms/phoneInputField/PhoneInputField.tsx
src/atoms/phoneInputField/helpers.ts
src/atoms/phoneInputField/index.ts
src/atoms/phoneInputField/phoneInputField.module.scss
src/atoms/phoneInputField/phoneInputField.stories.tsx
src/hooks/index.tsx
src/hooks/useValidate/index.ts
src/hooks/useValidate/useValidate.ts
src/hooks/useWizardForm/helpers.ts
src/hooks/useWizardForm/types.ts
src/hooks/useWizardForm/useWizardForm.tsx
src/hostedPages/activities/wizardForm/WizardForm.tsx
src/hostedPages/activities/wizardForm/wizardForm.spec.tsx
src/hostedPages/activities/wizardForm/wizardForm.stories.tsx
src/molecules/question/Question.tsx
src/molecules/question/types.ts
src/types/form.ts
src/types/generated/types-orchestration.tsx
yarn.lock

Changes:
- add PhoneInputField input
- add useValidate hook to provide functions for validating phone numbers (and can be expanded for other validation helpers that customers can use in a standalone way)
- add logic for including new PhoneInputField in form components
AST-4885

AST-4885 feat(inputs): add phone input and useValidate hook

---

package.json
src/atoms/scheduling/cal.com/CalDotComScheduling.tsx
src/atoms/scheduling/cal.com/calDotComTypes.tsx
yarn.lock

- Bump cal.com library version - it solves flickering/flashing issue (at least for me)
- Pass `booking` object in `onBookingSuccessful`
- Bump project version

Cal.com booking details

---

package.json
src/atoms/description/description.module.scss
src/atoms/richTextViewer/serializeHtml.ts
src/atoms/select/Select.tsx
src/atoms/select/select.stories.tsx
src/hostedPages/activities/message/message.module.scss

Changes:
- fix select value prop and logic for multiple
- adjust prefilled multiple story
- better handling of inline video embeds in message and description questions

Fix select form autosave multiple

---

.github/release-drafter-config.yaml
.github/workflows/npm-publish.yaml
.github/workflows/release-drafter.yaml

Changes:
- adds Release Drafter action
- remove release note creation step in npm publish workflow

chore(release_process): add release drafter and fix npm publish

---

.storybook/main.js
package.json
src/atoms/select/Select.tsx
src/atoms/select/select.module.scss
src/atoms/select/select.stories.tsx
yarn.lock

Changes:
- add autocomplete logic and UX changes to Select component (single and multiple types)
- remove `label` prop and replace with `labels` prop to extend support for more custom labels (placeholder, no options, error)
Other
- add StorySource add-on to Storybook to see story code in Storybook itself

AST-5007 feat(select): add autocomplete functionality

---

.github/release-drafter-config.yaml
.github/workflows/build-and-test.yaml
.github/workflows/chromatic.yaml
.github/workflows/release-drafter.yaml

Changes:
- add caching to speed up chromatic build step
- update autolabeler config for release drafter

ci(cache): cache node_modules for chromatic

---

.eslintrc
.prettierrc.json
package.json
src/atoms/select/Select.spec.tsx
src/atoms/select/Select.tsx
src/hostedPages/activities/wizardForm/__testdata__/testFormFixture.ts
src/hostedPages/activities/wizardForm/wizardForm.stories.tsx
src/molecules/question/Question.tsx

Changes:
- implement filtering and badge props on select answer inputs for multiple choice questions using this config
- add tests for select component
- add keyboard and a11y functionality to select

feat(select): implement filtering on select in wizard form

---

src/molecules/question/Question.tsx

Changes:
- if you partially fill in a phone number in an optional question, we still want to validate that it is a possible number
https://awellhealth.atlassian.net/browse/AST-5056

AST-5056 fix(question): validate partial phone number for optional questions

---

package.json
src/index.ts

Changes:
- export contents of types folder

chore(types): expose types folder

---

package.json
src/atoms/questionLabel/QuestionLabel.tsx
src/atoms/questionLabel/questionLabel.module.scss
src/hostedPages/activities/wizardForm/__testdata__/testFormFixture.ts
src/hostedPages/activities/wizardForm/wizardForm.stories.tsx
src/hostedPages/layouts/HostedPageLayout/HostedPageLayout.stories.tsx
src/hostedPages/layouts/HostedPageLayout/hostedPageLayout.module.scss
src/molecules/question/Question.tsx
yarn.lock

Changes:
- respect newline characters in question label/title strings
- add padding to activity content on mobile
Other Changes:
- clean up form fixture for wizard form story
- add viewport addon to storybook and set up mobile view stories
- removed unused DatePicker import
closes AST-5366

AST-5366 fix(form/question): fix question label and activity content spacing

---

src/atoms/progressIndicator/ProgressIndicator.tsx
src/atoms/progressIndicator/progressIndicator.module.scss
src/atoms/progressIndicator/progressIndicator.stories.tsx
src/hooks/useWizardForm/helpers.ts
src/hooks/useWizardForm/useWizardForm.tsx
src/hostedPages/activities/wizardForm/WizardForm.tsx
src/hostedPages/activities/wizardForm/__testdata__/testFormFixture.ts
src/hostedPages/activities/wizardForm/wizardForm.stories.tsx
src/hostedPages/layouts/HostedPageLayout/HostedPageLayout.tsx
src/molecules/question/Question.tsx

Changes:
- add visibleQuestions value to deps for useEffect that updates percentageCompleted value
- sensible defaults for showPercentage prop in ProgressIndicator
- remove unused validation logic for phone number questions and move to useWizardForm
- add prop to hide close button in HostedPagesLayout
- fix to form fixture used in Storybook (2 questions have same `id` which causes issues with local autosave)
- linting fixes

AST-5345 Progress Indicator and Form improvements

---

src/hostedPages/activities/wizardForm/wizardForm.spec.tsx

Changes:
- normalize labels used in tests
- add missing act() wrappers

tests(wizardForm): fix tests by using act() and normalizing labels

---

src/hostedPages/activities/wizardForm/WizardForm.tsx
src/molecules/question/Question.tsx
src/molecules/question/types.ts

AST-5378: submit and move to next question in case of boolean and multi-choice questions

---

src/molecules/question/Question.tsx

Auto focus on the input box when a question has an input field
Story book:

feat: Auto focus on the input box when a question has an input field

---

src/atoms/radioButton/RadioButton.tsx
src/hostedPages/activities/wizardForm/wizardForm.spec.tsx
src/molecules/question/Question.tsx
src/molecules/singleChoiceQuestion/SingleChoiceQuestion.tsx
src/molecules/singleChoiceQuestion/singleChoiceQuestion.module.scss

- Add delay of 750ms in radio option before moving to next question. (500ms seemed too less, and 1000ms too high).
- Add flickering animation to highlight the selected option
Demo: https://loom.com/share/f479d13e002749988ad7b9656db2ac72

feat: add flickering animation to radio option when a new option is selected

---

src/hostedPages/activities/form/ConversationalForm.tsx
src/hostedPages/activities/form/TraditionalForm.tsx
src/molecules/question/Question.tsx
src/molecules/question/types.ts

Add option to enable/disable move to next page and respective animation.

fix: enable animation for conversational form only

---

src/hooks/useForm/useConversationalForm.tsx

Reverting this change again since I do believe the new way is a lot more readable and reusable. And we realised this was not the reason for the issues we were facing on AHP.

Revert "Revert error handling on conversational form"

---

src/hostedPages/activities/form/ConversationalForm.tsx
src/hostedPages/activities/form/form.stories.tsx
src/molecules/question/Question.tsx
src/types/form.ts

to turn off/on auto progress
Demo: https://www.loom.com/share/48f43d9ea72d4fbeba038a7e9386a419

feat: add autoProgress param in ConversationalForm

---

src/atoms/rangeInput/RangeInput.tsx
src/atoms/rangeInput/rangeInput.module.scss
src/hostedPages/activities/form/__testdata__/eq5d5lFixture.ts

https://www.loom.com/share/7c72351766634bfeb98534673686dd04
https://www.loom.com/share/58770a82036c474288397d8d64633784

RangeInput: misc styling improvements and fixes

---

package.json
src/atoms/checkboxButton/CheckboxButton.tsx
src/atoms/logo/Logo.tsx
src/atoms/progressIndicator/ProgressIndicator.tsx
src/atoms/questionLabel/QuestionLabel.tsx
src/atoms/rangeInput/RangeInput.tsx
src/hostedPages/layouts/HostedPageLayout/HostedPageFooter/HostedPageFooter.tsx

docs(): add testing ids to various ui library components

---

src/molecules/singleChoiceQuestion/singleChoiceQuestion.module.scss

Fixes: 
https://www.loom.com/share/5451eaf705d84ecea92e936dde50946c

TP-203: fix blinking animation w/ auto-progress

---

src/atoms/phoneInputField/PhoneInputField.tsx
src/atoms/phoneInputField/helpers.ts

- make sure initialCountry is always available in countries list

fix(phoneInputField): country logic fix

---

package.json
src/hooks/useForm/types.ts
src/types/generated/types-orchestration.tsx

updating our schema to work for single and multi type option values

update schema for string type options

---

src/atoms/richTextViewer/richTextViewer.module.scss
src/constants/descriptionFixture.ts

https://product.cycle.app/app/awell/doc/feedback-from-sciensus-feb-19-2024-RG9jXzllMWJjOTAzLTZlODEtNDk5MC1hZTJlLWM2N2NjYzI5YThiNg==
https://www.loom.com/share/69a5b38ea9cc4c47befadc03d841691d

fix(css): remove spacing for first and last element in description

---

src/atoms/rangeInput/RangeInput.spec.tsx
src/atoms/rangeInput/RangeInput.tsx
src/atoms/rangeInput/rangeInput.module.scss
src/atoms/rangeInput/rangeInput.stories.tsx
src/constants/formFixture.ts
src/hostedPages/activities/form/TraditionalForm.tsx
src/hostedPages/activities/form/form.module.scss
src/molecules/question/Question.tsx
src/molecules/question/question.module.scss

Explanation and rationale behind the change: https://www.loom.com/share/3fcbd84132004ad0bc057ef097a981f6
Overall, the component is restructured and refactored with the hope it simplifies stuff for future changes.

TP-1369: fix range input styles

---

package.json

Bump package.json version for release

Upgrade package.json version

---

package.json
src/atoms/inputField/InputField.tsx
src/molecules/question/Question.tsx
src/molecules/question/helpers/isValidEmail.ts
src/types/generated/types-orchestration.tsx

Display email question type + implement validation logic for email type

ET-217: add support for email type user questions

---

src/hostedPages/activities/form/TraditionalForm.tsx

enhancement
___
- Added a new `questionLabels` prop to the `TraditionalForm` component to pass question labels to child components.
- Enhanced the form's ability to handle and display question labels dynamically.
___
<tr>
<td>
<details>
<summary><strong>TraditionalForm.tsx</strong><dd><code>Add question labels prop to TraditionalForm component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hostedPages/activities/form/TraditionalForm.tsx
<li>Added <code>questionLabels</code> prop to the <code>TraditionalForm</code> component.<br> <li> Passed <code>questionLabels</code> to child components for enhanced label handling.<br> <br>
</details>
</td> …

ET-288: pass question labels in traditional form to child components

---

package.json

enhancement
___
- Updated the version of the `@awell-health/ui-library` package from `0.1.68` to `0.1.70` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump version of UI library to 0.1.70</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the version of the <code>@awell-health/ui-library</code> package from <br><code>0.1.68</code> to <code>0.1.70</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/ui-library/pull/160/files#diff-7ae45ad102eab3b6 …

bump library version

---

package.json
src/atoms/scheduling/cal.com/CalDotComScheduling.tsx
yarn.lock

- update cal.com library
- By properly removing the event listener when the component unmounts or dependencies change, we prevent multiple listeners from being active simultaneously, which was causing the duplicate event triggers.
- In the cleanup function inside `useEffect`, we call `cal('off', { action: 'bookingSuccessful', callback: bookingSuccessfulCallback })` to remove the event listener.
___
Enhancement, Bug fix
___
- Improved event listener management in `CalDotComScheduling.tsx` by using `useRef` to track listener state and API reference, preventing duplicate event triggers.
- Implemented a cleanup function in `useEffect` to properly remove the event listener when the component unmounts or dependencies change.
- Updated the `@calcom/embed-react` library to version `^1.5.1` for …

fix(cal.com): remove the event listener when scheduling component unmounts

---

package.json
src/hostedPages/activities/form/TraditionalForm.tsx
src/hostedPages/activities/form/form.module.scss

https://www.loom.com/share/22aa587e73594594a0bac7b075d71910
___
enhancement
___
- Enhanced the `TraditionalForm` component by adding a scroll hint overlay to improve user experience.
- Moved the footer and submit button to a fixed position at the bottom of the form for better accessibility.
- Updated styles in `form.module.scss` to support the new scroll hint overlay and fixed footer positioning.
- Incremented the package version in `package.json` to reflect the changes.
___
<tr>
<td>
<details>
<summary><strong>TraditionalForm.tsx</strong><dd><code>Enhance form layout with scroll hint and fixed footer</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

TP-2543-change-where-the-button-is-on-forms

---

package.json
src/hostedPages/activities/form/TraditionalForm.tsx
src/hostedPages/activities/form/form.module.scss
src/hostedPages/layouts/HostedPageLayout/HostedPageFooter/HostedPageFooter.tsx
src/hostedPages/layouts/HostedPageLayout/HostedPageFooter/hostedPageFooter.module.scss

enhancement
___
- Refactored the `TraditionalForm` component to remove the fixed footer position and utilize the `fixPosition` prop in the `HostedPageFooter`.
- Introduced a new `fixPosition` prop in the `HostedPageFooter` component to control the footer's positioning dynamically.
- Updated SCSS styles to remove fixed positioning from the form module and added a `.fixed` class in the footer module for conditional styling.
___
<tr>
<td>
<details>
<summary><strong>TraditionalForm.tsx</strong><dd><code>Refactor footer positioning in TraditionalForm component</code>&nbsp; </dd></summary>
<hr>
src/hostedPages/activities/form/TraditionalForm.tsx
<li>Removed …

Tp 2543 change where the button is on forms

---

package.json
src/globalStyles/_variables.scss
src/hostedPages/activities/form/TraditionalForm.tsx
src/hostedPages/activities/form/form.module.scss

enhancement, bug fix
___
- Improved scroll detection logic in `TraditionalForm.tsx` for more accurate bottom detection.
- Changed the class name for the trademark div to ensure correct styling.
- Added a new spacing variable `--spacing-18` in `_variables.scss` for consistent spacing.
- Updated styles in `form.module.scss` to adjust padding and reduce the height of the scroll hint overlay.
- Bumped the package version to 0.1.74 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>TraditionalForm.tsx</strong><dd><code>Improve scroll handling and update trademark class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

make sure watermark is visible on transitional forms

---

package.json
src/atoms/phoneInputField/PhoneInputField.tsx

enhancement, configuration changes
___
- Introduced a new `forceDialCode` prop in the `PhoneInputField` component to prevent the country code from being deleted.
- Updated the `PhoneInputField` component to pass the `forceDialCode` prop to the `usePhoneInput` hook.
- Corrected the version number in `package.json` from `0.1.78` to `0.1.8`.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>PhoneInputField.tsx</strong><dd><code>Add `forceDialCode` prop to PhoneInputField component</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/atoms/phoneInputField/PhoneInputField.tsx
<li>Added a new <code>forceDialCode</code> prop …

add ability to force dial code

---

package.json
src/molecules/question/Question.tsx

enhancement
___
- Added the `forceDialCode` prop with a value of `true` to the `PhoneNumberInput` component in `Question.tsx` to enforce dial code usage.
- Updated the package version in `package.json` from `0.1.79` to `0.1.80`.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>Question.tsx</strong><dd><code>Add `forceDialCode` prop to PhoneNumberInput component</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/molecules/question/Question.tsx
<li>Added <code>forceDialCode</code> prop set to <code>true</code> in the <code>PhoneNumberInput</code> <br>component.<br>
</details>
</td>
<td><a …

add required field to phone number question

---

package.json
src/atoms/select/Select.tsx
src/constants/formFixture.ts
src/hostedPages/activities/form/TraditionalForm.tsx

Set parent div to `100%` that blocks select & other content to stretch for the right height
___
Bug fix, Enhancement
___
- Fixed an issue where the parent `div` in `TraditionalForm.tsx` did not stretch to the full height by setting its height to `100%`.
- Added a comment in `TraditionalForm.tsx` regarding the potential removal of the `div` wrapper as it breaks `100vh` height.
- Updated the package version in `package.json` from `0.1.84` to `0.1.85`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>TraditionalForm.tsx</strong><dd><code>Set parent `div` height to `100%` and added a comment</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

set parent div to 100% height

---

package.json
src/constants/formFixture.ts
src/hooks/useValidate/useValidate.ts

Set time to calendar date to avoid calculations based on timezone.
___
Bug fix, Enhancement
___
- Fixed an issue with date validation by appending a fixed time component (`T00:00:00`) to ensure consistent handling across timezones.
- Enhanced the form fixture by adding a new date question with specific configuration, including allowed dates and response date inclusion.
- Updated the package version to reflect the changes.
___
<tr>
<td>
<details>
<summary><strong>formFixture.ts</strong><dd><code>Add date question with allowed dates configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/constants/formFixture.ts …

Fix checking date in the past with different timezone

---

package.json
src/molecules/question/helpers/isValidEmail.ts

Enhancement, Bug fix
___
- Updated email validation regex to improve accuracy.
- Ensured email validation fails for invalid characters like `:`.
- Bumped package version from `0.1.87` to `0.1.88`.
___
<tr>
<td>
<details>
<summary><strong>isValidEmail.ts</strong><dd><code>Improve email validation regex</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/molecules/question/helpers/isValidEmail.ts
<li>Updated the email validation regex for stricter checks.<br> <li> Ensured invalid characters …

Improve email validation to fail when an email contains :
