package.json
src/atoms/rangeInput/RangeInput.spec.tsx
src/atoms/rangeInput/RangeInput.tsx

Followed this guide to add the labels to the component: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_labels
Tested with:
{
max_label: `null`,
min_label: `null`
}
and
{
max_label: `undefined`,
min_label: `undefined`
}

feat(): add labels in RangeInput for min and max

---

package.json
src/atoms/select/Select.tsx
src/atoms/select/select.module.scss
src/atoms/select/select.stories.tsx
src/hostedPages/activities/wizardForm/WizardForm.tsx
src/molecules/question/Question.tsx
src/types/generated/types-orchestration.tsx

Changes:
- bump lib to v0.60
- add Select to WizardForm (via Question component)
- update Select to explicitly accept `value` prop (to support form autosave)
- handle select as a controlled input (i.e. value of select can be prefilled)
- codegen on latest release
NB: Select component does not support autocomplete (not based on MUI autocomplete component)

AST-4990 feat(question): add select implementation

---

package.json
src/atoms/select/select.stories.tsx
src/hooks/useWizardForm/useWizardForm.tsx

https://awellhealth.atlassian.net/browse/AST-5010
Changes:
- in the same way that we assess whether to show a next question before submitting, we also assess whether to submit when handling showing the next question
- bump to 0.0.63
NB: because these updates are await-ed, there's no risk that we submit the form too early. there's also the likely failsafe of form errors (e.g required questions not being answered) that will block form submission if this somehow happened.

AST-5010: Handle last question being hidden when 2nd last question answer is updated

---

src/atoms/datePicker/DatePicker.tsx
src/atoms/datePicker/datePicker.stories.tsx
src/atoms/themeProvider/ThemeProvider.tsx
src/hostedPages/activities/wizardForm/__testdata__/testFormFixture.ts
src/hostedPages/activities/wizardForm/wizardForm.stories.tsx
src/molecules/question/Question.tsx

Changes:
- replace DatePicker component for date questions with native input field (date type) -- this uses the browser's native date picker UI to render the input and picker, which is what we use in Studio/Care
- remove `Date Picker` story and add `Input Field` sub-story for date type inputs
- add deprecated warning to DatePicker component
NB: this is a quick fix for the alignment issue with little downside, we can always revisit the choice of date picker down the line

AST-5003 fix(date-picker): replace date picker with input field

---

src/atoms/inputField/InputField.tsx
src/atoms/longTextField/LongTextField.tsx
src/atoms/phoneInputField/PhoneInputField.tsx
src/atoms/select/Select.tsx

Issue:
- a user reported seeing inputs respond in a RTL fashion (https://awellhealth.slack.com/archives/C03TYH8B20P/p1681287134968239)
Solution:
- while we cannot 'force' LTR and the user's device settings are always prioritised, we can suggest LTR to reduce the likelihood that the browser is unclear on which way inputs should be rendered
Changes:
- right now we only support LTR languages so inputs should default to LTR

AST-5099: add dir="ltr" to inputs

---

.gitignore
package.json
rollup.config.js
src/atoms/logo/Logo.tsx
src/hostedPages/layouts/HostedPageLayout/HostedPageLayout.tsx
src/molecules/navbar/Navbar.tsx

This are changes needed by `react-sdk`.
1. Changes to logo - allow react component to be passed instead of just string
2. CSS class name generation -  see `rollup.config.js` and lookup `generateScopedName`. `postcss` by default creates class names with hash so it won't work when styling externally. This change ensures proper class names. 
- Added `awell__` prefix - please change if not wanted

Sdk changes

---

package.json
src/hostedPages/layouts/HostedPageLayout/CloseButton/CloseButton.tsx

Simple modification to CloseButton component to allow it to be selected with a static reference (e.g. getElementById). This enables hiding the component if needed in an embedded AHP instance.
NB: No visual or functional changes
Changes:
- add `id` property to CloseButton component outermost element
- bump package version to v0.1.10
AST-5323

AST-5323 feat(CloseButton): add id to close button to simplify css selection

---

package.json
src/atoms/rangeInput/RangeInput.tsx
src/atoms/rangeInput/rangeInput.module.scss

**Changes:**
RangeInput component
- use initial question value (if present) to set tooltip position and value
- add more space for tooltip and move it slightly higher off of slider track
closes AST-5331

fix(rangeInput): show tooltip on initial value and add space

---

package.json
src/atoms/rangeInput/RangeInput.tsx
src/atoms/rangeInput/rangeInput.module.scss

Changes:
- with introduction of instruction to select value on tooltip, we need to preserve the spacing between the label and input, regardless of whether the value tooltip is set to be shown or not

fix(rangeInput): preserve spacing even when value tooltip is not displayed

---

package.json
src/hooks/useForm/useConversationalForm.tsx
src/hooks/useForm/useTraditionalForm.tsx

The `questions` object is modified from outside the Form component and that causes a call to evaluateFormRules.
To prevent calling the evaluateFormRules, we need to make sure the reference is deep copy of `questions`, not shallow copy.

Avoid running evaluation rule when there are no changes in question

---

package.json
src/hostedPages/activities/form/ConversationalForm.tsx
src/hostedPages/activities/form/TraditionalForm.tsx
src/hostedPages/activities/form/form.stories.tsx

This PR changes the loader in Conversational & Traditional Form to be the same as we have in the hosted pages app.

feat(form): use the same loader in forms as we have in hosted pages app

---

package.json
src/hooks/useForm/helpers.ts
src/hooks/useForm/types.ts
src/hooks/useForm/useConversationalForm.tsx
src/hooks/useForm/useTraditionalForm.tsx
src/hooks/useValidate/useValidate.test.ts
src/hooks/useValidate/useValidate.ts
src/molecules/question/Question.tsx
src/molecules/question/helpers/getMaxValueForDateInput.ts
src/molecules/question/helpers/getMinValueForDateInput.ts
src/types/generated/types-orchestration.tsx

- Add new validation rule for date responses
- User sees an error when date response value violates one of the rules defined in the question configuration.
- Add min/max date restriction in calendar input.
- All invalid dates are blurred in the calendar UI.

TP-1300: add validation for date question in form response

---

package.json
src/hooks/useForm/helpers.ts
src/hooks/useForm/useConversationalForm.tsx
src/hooks/useForm/useTraditionalForm.tsx

We should not submit hidden fields or not yet touched fields when evaluating visiblity conditions, because default values for those fields will lead wrongly evaluated conditions, espicially for is_none_of operator

fix: submit only dirty form fields when evaluating visibility rules

---

src/atoms/rangeInput/RangeInput.tsx

This sets value on the input render. Prev logic was a bit weird when input stayed uncontrolled and logic was based not on the value but touch event. 
@nckhell Is there a way to Q&A it? This Component logic os not intuitive at all with many states and some unnecessary stuff IMHO.

[tp-1640-fix-rangeinput-slider] Set values based component render

---

src/hostedPages/activities/form/form.module.scss

the padding from the trademark is necessary; unfortunately, storybook and actual deployment in hosted pages is inconsistent
___
enhancement
___
- Increased the bottom padding of the `.trademark` class in the SCSS file to ensure consistent styling across different environments, such as Storybook and actual deployments.
___
<tr>
<td>
<details>
<summary><strong>form.module.scss</strong><dd><code>Increase bottom padding for trademark class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hostedPages/activities/form/form.module.scss
<li>Increased bottom padding for the …

fix(trademark): bump padding in trademark

---

package.json
src/hostedPages/layouts/HostedPageLayout/hostedPageLayout.module.scss

with the new fixed bottom next button, the margin-bottom made it difficult to see at 500px or smaller height
___
enhancement
___
- Removed the media query that adjusted the margin-bottom for screens with a max-height of 500px in the `hostedPageLayout.module.scss` file, improving layout consistency.
- Updated the package version in `package.json` from 0.1.76 to 0.1.77 to reflect the changes.
___
<tr>
<td>
<details>
<summary><strong>hostedPageLayout.module.scss</strong><dd><code>Remove margin-bottom adjustment for small heights</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

remove 500px height media break

---

package.json
src/molecules/question/Question.tsx

Bug fix
___
- Fixed email validation to only validate when the email field is non-empty.
- Changed the input type from `email` to `text` to prevent automatic browser validation.
- Updated the package version in `package.json` to 0.1.78.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Question.tsx</strong><dd><code>Fix email validation and input type handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/molecules/question/Question.tsx
<li>Added <code>isEmpty</code> check before validating email.<br> <li> Changed input type from <code>email</code> to <code>text</code>.<br> <li> Set default …

fix(form): only validate email address when it is non-empty

---

package.json
src/atoms/richTextViewer/RichTextViewer.tsx

enhancement
___
- Enhanced the `RichTextViewer` component to convert escaped newline characters (`\n`) into HTML line breaks (`<br />`).
- This change ensures that multiline strings are displayed correctly in HTML.
- Added a detailed comment explaining the transformation process and its purpose.
___
<tr>
<td>
<details>
<summary><strong>RichTextViewer.tsx</strong><dd><code>Convert escaped newlines to HTML line breaks in RichTextViewer</code></dd></summary>
<hr>
src/atoms/richTextViewer/RichTextViewer.tsx
<li>Added logic to convert escaped newline characters to HTML line breaks.<br> <li> Updated the <code>dangerouslySetInnerHTML</code> to use the modified …

ET-495: preserve line breaks in escaped strings

---

src/atoms/phoneInputField/PhoneInputField.tsx

Allows to paste input phone value in a various formats, that are parsed by helper library, before triggering `onChange` prop.
___
enhancement
___
- Introduced a `useEffect` hook to ensure the `onChange` prop is triggered whenever the `phone` value is updated, improving the handling of formatted phone numbers.
- Removed the redundant `onChange` call from the `handleInputChange` function, streamlining the code.
___
<tr>
<td>
<details>
<summary><strong>PhoneInputField.tsx</strong><dd><code>Enhance phone input handling with <code>useEffect</code> for formatted value <br>updates</code></dd></summary>
<hr>
src/atoms/phoneInputField/PhoneInputField.tsx
<li>Added …

Update on change hook after phone is formatted by library

---

package.json
src/atoms/phoneInputField/PhoneInputField.tsx

bug_fix
___
- Fixed the `onChange` callback behavior in the `PhoneInputField` component by replacing the `useEffect` hook with a direct `onPhoneUpdate` callback.
- Simplified the phone number update logic to ensure proper handling of changes.
- Updated the package version in `package.json` to `0.1.86`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>PhoneInputField.tsx</strong><dd><code>Refactor phone input field to fix onChange callback behavior</code></dd></summary>
<hr>
src/atoms/phoneInputField/PhoneInputField.tsx
<li>Replaced the <code>useEffect</code> hook with a direct <code>onPhoneUpdate</code> callback to <br>handle phone number updates.<br> <li> Simplified …

Change the onChange callback on phone input
